/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EBackupScriptProcessingMode Scenario for scripts execution.
type EBackupScriptProcessingMode string

// List of EBackupScriptProcessingMode
const (
	EBACKUPSCRIPTPROCESSINGMODE_DISABLE_EXEC EBackupScriptProcessingMode = "disableExec"
	EBACKUPSCRIPTPROCESSINGMODE_IGNORE_EXEC_FAILURES EBackupScriptProcessingMode = "ignoreExecFailures"
	EBACKUPSCRIPTPROCESSINGMODE_REQUIRE_SUCCESS EBackupScriptProcessingMode = "requireSuccess"
)

// All allowed values of EBackupScriptProcessingMode enum
var AllowedEBackupScriptProcessingModeEnumValues = []EBackupScriptProcessingMode{
	"disableExec",
	"ignoreExecFailures",
	"requireSuccess",
}

func (v *EBackupScriptProcessingMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EBackupScriptProcessingMode(value)
	for _, existing := range AllowedEBackupScriptProcessingModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EBackupScriptProcessingMode", value)
}

// NewEBackupScriptProcessingModeFromValue returns a pointer to a valid EBackupScriptProcessingMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEBackupScriptProcessingModeFromValue(v string) (*EBackupScriptProcessingMode, error) {
	ev := EBackupScriptProcessingMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EBackupScriptProcessingMode: valid values are %v", v, AllowedEBackupScriptProcessingModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EBackupScriptProcessingMode) IsValid() bool {
	for _, existing := range AllowedEBackupScriptProcessingModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EBackupScriptProcessingMode value
func (v EBackupScriptProcessingMode) Ptr() *EBackupScriptProcessingMode {
	return &v
}

type NullableEBackupScriptProcessingMode struct {
	value *EBackupScriptProcessingMode
	isSet bool
}

func (v NullableEBackupScriptProcessingMode) Get() *EBackupScriptProcessingMode {
	return v.value
}

func (v *NullableEBackupScriptProcessingMode) Set(val *EBackupScriptProcessingMode) {
	v.value = val
	v.isSet = true
}

func (v NullableEBackupScriptProcessingMode) IsSet() bool {
	return v.isSet
}

func (v *NullableEBackupScriptProcessingMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEBackupScriptProcessingMode(val *EBackupScriptProcessingMode) *NullableEBackupScriptProcessingMode {
	return &NullableEBackupScriptProcessingMode{value: val, isSet: true}
}

func (v NullableEBackupScriptProcessingMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEBackupScriptProcessingMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

