/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev2
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EVmwareFcdInstantRecoveryMountsFiltersOrderColumn the model 'EVmwareFcdInstantRecoveryMountsFiltersOrderColumn'
type EVmwareFcdInstantRecoveryMountsFiltersOrderColumn string

// List of EVmwareFcdInstantRecoveryMountsFiltersOrderColumn
const (
	EVMWAREFCDINSTANTRECOVERYMOUNTSFILTERSORDERCOLUMN_STATE EVmwareFcdInstantRecoveryMountsFiltersOrderColumn = "state"
	EVMWAREFCDINSTANTRECOVERYMOUNTSFILTERSORDERCOLUMN_NAME EVmwareFcdInstantRecoveryMountsFiltersOrderColumn = "name"
)

func (v *EVmwareFcdInstantRecoveryMountsFiltersOrderColumn) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EVmwareFcdInstantRecoveryMountsFiltersOrderColumn(value)
	for _, existing := range []EVmwareFcdInstantRecoveryMountsFiltersOrderColumn{ "state", "name",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EVmwareFcdInstantRecoveryMountsFiltersOrderColumn", value)
}

// Ptr returns reference to EVmwareFcdInstantRecoveryMountsFiltersOrderColumn value
func (v EVmwareFcdInstantRecoveryMountsFiltersOrderColumn) Ptr() *EVmwareFcdInstantRecoveryMountsFiltersOrderColumn {
	return &v
}

type NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn struct {
	value *EVmwareFcdInstantRecoveryMountsFiltersOrderColumn
	isSet bool
}

func (v NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn) Get() *EVmwareFcdInstantRecoveryMountsFiltersOrderColumn {
	return v.value
}

func (v *NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn) Set(val *EVmwareFcdInstantRecoveryMountsFiltersOrderColumn) {
	v.value = val
	v.isSet = true
}

func (v NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn) IsSet() bool {
	return v.isSet
}

func (v *NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn(val *EVmwareFcdInstantRecoveryMountsFiltersOrderColumn) *NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn {
	return &NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn{value: val, isSet: true}
}

func (v NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEVmwareFcdInstantRecoveryMountsFiltersOrderColumn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

