/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev1
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EPeriodicallyKinds Time unit for periodic job scheduling.
type EPeriodicallyKinds string

// List of EPeriodicallyKinds
const (
	EPERIODICALLYKINDS_HOURS EPeriodicallyKinds = "Hours"
	EPERIODICALLYKINDS_MINUTES EPeriodicallyKinds = "Minutes"
	EPERIODICALLYKINDS_SECONDS EPeriodicallyKinds = "Seconds"
	EPERIODICALLYKINDS_DAYS EPeriodicallyKinds = "Days"
)

func (v *EPeriodicallyKinds) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EPeriodicallyKinds(value)
	for _, existing := range []EPeriodicallyKinds{ "Hours", "Minutes", "Seconds", "Days",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EPeriodicallyKinds", value)
}

// Ptr returns reference to EPeriodicallyKinds value
func (v EPeriodicallyKinds) Ptr() *EPeriodicallyKinds {
	return &v
}

type NullableEPeriodicallyKinds struct {
	value *EPeriodicallyKinds
	isSet bool
}

func (v NullableEPeriodicallyKinds) Get() *EPeriodicallyKinds {
	return v.value
}

func (v *NullableEPeriodicallyKinds) Set(val *EPeriodicallyKinds) {
	v.value = val
	v.isSet = true
}

func (v NullableEPeriodicallyKinds) IsSet() bool {
	return v.isSet
}

func (v *NullableEPeriodicallyKinds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEPeriodicallyKinds(val *EPeriodicallyKinds) *NullableEPeriodicallyKinds {
	return &NullableEPeriodicallyKinds{value: val, isSet: true}
}

func (v NullableEPeriodicallyKinds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEPeriodicallyKinds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

