/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EGuestOSType Type of the guest OS.
type EGuestOSType string

// List of EGuestOSType
const (
	EGUESTOSTYPE_WINDOWS EGuestOSType = "Windows"
	EGUESTOSTYPE_LINUX EGuestOSType = "Linux"
)

// All allowed values of EGuestOSType enum
var AllowedEGuestOSTypeEnumValues = []EGuestOSType{
	"Windows",
	"Linux",
}

func (v *EGuestOSType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EGuestOSType(value)
	for _, existing := range AllowedEGuestOSTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EGuestOSType", value)
}

// NewEGuestOSTypeFromValue returns a pointer to a valid EGuestOSType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEGuestOSTypeFromValue(v string) (*EGuestOSType, error) {
	ev := EGuestOSType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EGuestOSType: valid values are %v", v, AllowedEGuestOSTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EGuestOSType) IsValid() bool {
	for _, existing := range AllowedEGuestOSTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EGuestOSType value
func (v EGuestOSType) Ptr() *EGuestOSType {
	return &v
}

type NullableEGuestOSType struct {
	value *EGuestOSType
	isSet bool
}

func (v NullableEGuestOSType) Get() *EGuestOSType {
	return v.value
}

func (v *NullableEGuestOSType) Set(val *EGuestOSType) {
	v.value = val
	v.isSet = true
}

func (v NullableEGuestOSType) IsSet() bool {
	return v.isSet
}

func (v *NullableEGuestOSType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEGuestOSType(val *EGuestOSType) *NullableEGuestOSType {
	return &NullableEGuestOSType{value: val, isSet: true}
}

func (v NullableEGuestOSType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEGuestOSType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

