/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev2
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ERepositoryExtentStatusType the model 'ERepositoryExtentStatusType'
type ERepositoryExtentStatusType string

// List of ERepositoryExtentStatusType
const (
	EREPOSITORYEXTENTSTATUSTYPE_NORMAL ERepositoryExtentStatusType = "Normal"
	EREPOSITORYEXTENTSTATUSTYPE_EVACUATE ERepositoryExtentStatusType = "Evacuate"
	EREPOSITORYEXTENTSTATUSTYPE_PENDING ERepositoryExtentStatusType = "Pending"
	EREPOSITORYEXTENTSTATUSTYPE_SEALED ERepositoryExtentStatusType = "Sealed"
	EREPOSITORYEXTENTSTATUSTYPE_MAINTENANCE ERepositoryExtentStatusType = "Maintenance"
)

func (v *ERepositoryExtentStatusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ERepositoryExtentStatusType(value)
	for _, existing := range []ERepositoryExtentStatusType{ "Normal", "Evacuate", "Pending", "Sealed", "Maintenance",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ERepositoryExtentStatusType", value)
}

// Ptr returns reference to ERepositoryExtentStatusType value
func (v ERepositoryExtentStatusType) Ptr() *ERepositoryExtentStatusType {
	return &v
}

type NullableERepositoryExtentStatusType struct {
	value *ERepositoryExtentStatusType
	isSet bool
}

func (v NullableERepositoryExtentStatusType) Get() *ERepositoryExtentStatusType {
	return v.value
}

func (v *NullableERepositoryExtentStatusType) Set(val *ERepositoryExtentStatusType) {
	v.value = val
	v.isSet = true
}

func (v NullableERepositoryExtentStatusType) IsSet() bool {
	return v.isSet
}

func (v *NullableERepositoryExtentStatusType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableERepositoryExtentStatusType(val *ERepositoryExtentStatusType) *NullableERepositoryExtentStatusType {
	return &NullableERepositoryExtentStatusType{value: val, isSet: true}
}

func (v NullableERepositoryExtentStatusType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableERepositoryExtentStatusType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

