/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ScheduleMonthlyModel Monthly scheduling options.
type ScheduleMonthlyModel struct {
	// If *true*, monthly schedule is enabled.
	IsEnabled bool `json:"isEnabled"`
	// Local time when the job must start.
	LocalTime *string `json:"localTime,omitempty"`
	DayOfWeek *EDayOfWeek `json:"dayOfWeek,omitempty"`
	DayNumberInMonth *EDayNumberInMonth `json:"dayNumberInMonth,omitempty"`
	// Day of the month when the job must start.
	DayOfMonth *int32 `json:"dayOfMonth,omitempty"`
	// Months when the job must start.
	Months []EMonth `json:"months,omitempty"`
}

// NewScheduleMonthlyModel instantiates a new ScheduleMonthlyModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleMonthlyModel(isEnabled bool) *ScheduleMonthlyModel {
	this := ScheduleMonthlyModel{}
	this.IsEnabled = isEnabled
	return &this
}

// NewScheduleMonthlyModelWithDefaults instantiates a new ScheduleMonthlyModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleMonthlyModelWithDefaults() *ScheduleMonthlyModel {
	this := ScheduleMonthlyModel{}
	var isEnabled bool = false
	this.IsEnabled = isEnabled
	return &this
}

// GetIsEnabled returns the IsEnabled field value
func (o *ScheduleMonthlyModel) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *ScheduleMonthlyModel) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *ScheduleMonthlyModel) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetLocalTime returns the LocalTime field value if set, zero value otherwise.
func (o *ScheduleMonthlyModel) GetLocalTime() string {
	if o == nil || isNil(o.LocalTime) {
		var ret string
		return ret
	}
	return *o.LocalTime
}

// GetLocalTimeOk returns a tuple with the LocalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleMonthlyModel) GetLocalTimeOk() (*string, bool) {
	if o == nil || isNil(o.LocalTime) {
    return nil, false
	}
	return o.LocalTime, true
}

// HasLocalTime returns a boolean if a field has been set.
func (o *ScheduleMonthlyModel) HasLocalTime() bool {
	if o != nil && !isNil(o.LocalTime) {
		return true
	}

	return false
}

// SetLocalTime gets a reference to the given string and assigns it to the LocalTime field.
func (o *ScheduleMonthlyModel) SetLocalTime(v string) {
	o.LocalTime = &v
}

// GetDayOfWeek returns the DayOfWeek field value if set, zero value otherwise.
func (o *ScheduleMonthlyModel) GetDayOfWeek() EDayOfWeek {
	if o == nil || isNil(o.DayOfWeek) {
		var ret EDayOfWeek
		return ret
	}
	return *o.DayOfWeek
}

// GetDayOfWeekOk returns a tuple with the DayOfWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleMonthlyModel) GetDayOfWeekOk() (*EDayOfWeek, bool) {
	if o == nil || isNil(o.DayOfWeek) {
    return nil, false
	}
	return o.DayOfWeek, true
}

// HasDayOfWeek returns a boolean if a field has been set.
func (o *ScheduleMonthlyModel) HasDayOfWeek() bool {
	if o != nil && !isNil(o.DayOfWeek) {
		return true
	}

	return false
}

// SetDayOfWeek gets a reference to the given EDayOfWeek and assigns it to the DayOfWeek field.
func (o *ScheduleMonthlyModel) SetDayOfWeek(v EDayOfWeek) {
	o.DayOfWeek = &v
}

// GetDayNumberInMonth returns the DayNumberInMonth field value if set, zero value otherwise.
func (o *ScheduleMonthlyModel) GetDayNumberInMonth() EDayNumberInMonth {
	if o == nil || isNil(o.DayNumberInMonth) {
		var ret EDayNumberInMonth
		return ret
	}
	return *o.DayNumberInMonth
}

// GetDayNumberInMonthOk returns a tuple with the DayNumberInMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleMonthlyModel) GetDayNumberInMonthOk() (*EDayNumberInMonth, bool) {
	if o == nil || isNil(o.DayNumberInMonth) {
    return nil, false
	}
	return o.DayNumberInMonth, true
}

// HasDayNumberInMonth returns a boolean if a field has been set.
func (o *ScheduleMonthlyModel) HasDayNumberInMonth() bool {
	if o != nil && !isNil(o.DayNumberInMonth) {
		return true
	}

	return false
}

// SetDayNumberInMonth gets a reference to the given EDayNumberInMonth and assigns it to the DayNumberInMonth field.
func (o *ScheduleMonthlyModel) SetDayNumberInMonth(v EDayNumberInMonth) {
	o.DayNumberInMonth = &v
}

// GetDayOfMonth returns the DayOfMonth field value if set, zero value otherwise.
func (o *ScheduleMonthlyModel) GetDayOfMonth() int32 {
	if o == nil || isNil(o.DayOfMonth) {
		var ret int32
		return ret
	}
	return *o.DayOfMonth
}

// GetDayOfMonthOk returns a tuple with the DayOfMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleMonthlyModel) GetDayOfMonthOk() (*int32, bool) {
	if o == nil || isNil(o.DayOfMonth) {
    return nil, false
	}
	return o.DayOfMonth, true
}

// HasDayOfMonth returns a boolean if a field has been set.
func (o *ScheduleMonthlyModel) HasDayOfMonth() bool {
	if o != nil && !isNil(o.DayOfMonth) {
		return true
	}

	return false
}

// SetDayOfMonth gets a reference to the given int32 and assigns it to the DayOfMonth field.
func (o *ScheduleMonthlyModel) SetDayOfMonth(v int32) {
	o.DayOfMonth = &v
}

// GetMonths returns the Months field value if set, zero value otherwise.
func (o *ScheduleMonthlyModel) GetMonths() []EMonth {
	if o == nil || isNil(o.Months) {
		var ret []EMonth
		return ret
	}
	return o.Months
}

// GetMonthsOk returns a tuple with the Months field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleMonthlyModel) GetMonthsOk() ([]EMonth, bool) {
	if o == nil || isNil(o.Months) {
    return nil, false
	}
	return o.Months, true
}

// HasMonths returns a boolean if a field has been set.
func (o *ScheduleMonthlyModel) HasMonths() bool {
	if o != nil && !isNil(o.Months) {
		return true
	}

	return false
}

// SetMonths gets a reference to the given []EMonth and assigns it to the Months field.
func (o *ScheduleMonthlyModel) SetMonths(v []EMonth) {
	o.Months = v
}

func (o ScheduleMonthlyModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	if !isNil(o.LocalTime) {
		toSerialize["localTime"] = o.LocalTime
	}
	if !isNil(o.DayOfWeek) {
		toSerialize["dayOfWeek"] = o.DayOfWeek
	}
	if !isNil(o.DayNumberInMonth) {
		toSerialize["dayNumberInMonth"] = o.DayNumberInMonth
	}
	if !isNil(o.DayOfMonth) {
		toSerialize["dayOfMonth"] = o.DayOfMonth
	}
	if !isNil(o.Months) {
		toSerialize["months"] = o.Months
	}
	return json.Marshal(toSerialize)
}

type NullableScheduleMonthlyModel struct {
	value *ScheduleMonthlyModel
	isSet bool
}

func (v NullableScheduleMonthlyModel) Get() *ScheduleMonthlyModel {
	return v.value
}

func (v *NullableScheduleMonthlyModel) Set(val *ScheduleMonthlyModel) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleMonthlyModel) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleMonthlyModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleMonthlyModel(val *ScheduleMonthlyModel) *NullableScheduleMonthlyModel {
	return &NullableScheduleMonthlyModel{value: val, isSet: true}
}

func (v NullableScheduleMonthlyModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleMonthlyModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


