/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureComputeCredentialsExistingAccountSpec Existing Azure Active Directory application.
type AzureComputeCredentialsExistingAccountSpec struct {
	Deployment AzureComputeCloudCredentialsDeploymentModel `json:"deployment"`
	Subscription AzureComputeCloudCredentialsSubscriptionSpec `json:"subscription"`
}

// NewAzureComputeCredentialsExistingAccountSpec instantiates a new AzureComputeCredentialsExistingAccountSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureComputeCredentialsExistingAccountSpec(deployment AzureComputeCloudCredentialsDeploymentModel, subscription AzureComputeCloudCredentialsSubscriptionSpec) *AzureComputeCredentialsExistingAccountSpec {
	this := AzureComputeCredentialsExistingAccountSpec{}
	this.Deployment = deployment
	this.Subscription = subscription
	return &this
}

// NewAzureComputeCredentialsExistingAccountSpecWithDefaults instantiates a new AzureComputeCredentialsExistingAccountSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureComputeCredentialsExistingAccountSpecWithDefaults() *AzureComputeCredentialsExistingAccountSpec {
	this := AzureComputeCredentialsExistingAccountSpec{}
	return &this
}

// GetDeployment returns the Deployment field value
func (o *AzureComputeCredentialsExistingAccountSpec) GetDeployment() AzureComputeCloudCredentialsDeploymentModel {
	if o == nil {
		var ret AzureComputeCloudCredentialsDeploymentModel
		return ret
	}

	return o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCredentialsExistingAccountSpec) GetDeploymentOk() (*AzureComputeCloudCredentialsDeploymentModel, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Deployment, true
}

// SetDeployment sets field value
func (o *AzureComputeCredentialsExistingAccountSpec) SetDeployment(v AzureComputeCloudCredentialsDeploymentModel) {
	o.Deployment = v
}

// GetSubscription returns the Subscription field value
func (o *AzureComputeCredentialsExistingAccountSpec) GetSubscription() AzureComputeCloudCredentialsSubscriptionSpec {
	if o == nil {
		var ret AzureComputeCloudCredentialsSubscriptionSpec
		return ret
	}

	return o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCredentialsExistingAccountSpec) GetSubscriptionOk() (*AzureComputeCloudCredentialsSubscriptionSpec, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Subscription, true
}

// SetSubscription sets field value
func (o *AzureComputeCredentialsExistingAccountSpec) SetSubscription(v AzureComputeCloudCredentialsSubscriptionSpec) {
	o.Subscription = v
}

func (o AzureComputeCredentialsExistingAccountSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["deployment"] = o.Deployment
	}
	if true {
		toSerialize["subscription"] = o.Subscription
	}
	return json.Marshal(toSerialize)
}

type NullableAzureComputeCredentialsExistingAccountSpec struct {
	value *AzureComputeCredentialsExistingAccountSpec
	isSet bool
}

func (v NullableAzureComputeCredentialsExistingAccountSpec) Get() *AzureComputeCredentialsExistingAccountSpec {
	return v.value
}

func (v *NullableAzureComputeCredentialsExistingAccountSpec) Set(val *AzureComputeCredentialsExistingAccountSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureComputeCredentialsExistingAccountSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureComputeCredentialsExistingAccountSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureComputeCredentialsExistingAccountSpec(val *AzureComputeCredentialsExistingAccountSpec) *NullableAzureComputeCredentialsExistingAccountSpec {
	return &NullableAzureComputeCredentialsExistingAccountSpec{value: val, isSet: true}
}

func (v NullableAzureComputeCredentialsExistingAccountSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureComputeCredentialsExistingAccountSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


