/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RepositoryStatesFilters Filters repositories by the specified parameters.
type RepositoryStatesFilters struct {
	// Skips the specified number of repositories.
	Skip *int32 `json:"skip,omitempty"`
	// Returns the specified number of repositories.
	Limit *int32 `json:"limit,omitempty"`
	OrderColumn *ERepositoryStatesFiltersOrderColumn `json:"orderColumn,omitempty"`
	// Sorts repositories in the ascending order by the `orderColumn` parameter.
	OrderAsc *bool `json:"orderAsc,omitempty"`
	IdFilter *string `json:"idFilter,omitempty"`
	// Filters repositories by the `nameFilter` pattern. The pattern can match any repository parameter. To substitute one or more characters, use the asterisk (*) character at the beginning and/or at the end.
	NameFilter *string `json:"nameFilter,omitempty"`
	TypeFilter *ERepositoryType `json:"typeFilter,omitempty"`
	// Filters repositories by repository capacity.
	CapacityFilter *float64 `json:"capacityFilter,omitempty"`
	// Filters repositories by repository free space.
	FreeSpaceFilter *float64 `json:"freeSpaceFilter,omitempty"`
	// Filters repositories by repository used space.
	UsedSpaceFilter *float64 `json:"usedSpaceFilter,omitempty"`
}

// NewRepositoryStatesFilters instantiates a new RepositoryStatesFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryStatesFilters() *RepositoryStatesFilters {
	this := RepositoryStatesFilters{}
	return &this
}

// NewRepositoryStatesFiltersWithDefaults instantiates a new RepositoryStatesFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryStatesFiltersWithDefaults() *RepositoryStatesFilters {
	this := RepositoryStatesFilters{}
	return &this
}

// GetSkip returns the Skip field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetSkip() int32 {
	if o == nil || isNil(o.Skip) {
		var ret int32
		return ret
	}
	return *o.Skip
}

// GetSkipOk returns a tuple with the Skip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetSkipOk() (*int32, bool) {
	if o == nil || isNil(o.Skip) {
    return nil, false
	}
	return o.Skip, true
}

// HasSkip returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasSkip() bool {
	if o != nil && !isNil(o.Skip) {
		return true
	}

	return false
}

// SetSkip gets a reference to the given int32 and assigns it to the Skip field.
func (o *RepositoryStatesFilters) SetSkip(v int32) {
	o.Skip = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetLimit() int32 {
	if o == nil || isNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetLimitOk() (*int32, bool) {
	if o == nil || isNil(o.Limit) {
    return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasLimit() bool {
	if o != nil && !isNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *RepositoryStatesFilters) SetLimit(v int32) {
	o.Limit = &v
}

// GetOrderColumn returns the OrderColumn field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetOrderColumn() ERepositoryStatesFiltersOrderColumn {
	if o == nil || isNil(o.OrderColumn) {
		var ret ERepositoryStatesFiltersOrderColumn
		return ret
	}
	return *o.OrderColumn
}

// GetOrderColumnOk returns a tuple with the OrderColumn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetOrderColumnOk() (*ERepositoryStatesFiltersOrderColumn, bool) {
	if o == nil || isNil(o.OrderColumn) {
    return nil, false
	}
	return o.OrderColumn, true
}

// HasOrderColumn returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasOrderColumn() bool {
	if o != nil && !isNil(o.OrderColumn) {
		return true
	}

	return false
}

// SetOrderColumn gets a reference to the given ERepositoryStatesFiltersOrderColumn and assigns it to the OrderColumn field.
func (o *RepositoryStatesFilters) SetOrderColumn(v ERepositoryStatesFiltersOrderColumn) {
	o.OrderColumn = &v
}

// GetOrderAsc returns the OrderAsc field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetOrderAsc() bool {
	if o == nil || isNil(o.OrderAsc) {
		var ret bool
		return ret
	}
	return *o.OrderAsc
}

// GetOrderAscOk returns a tuple with the OrderAsc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetOrderAscOk() (*bool, bool) {
	if o == nil || isNil(o.OrderAsc) {
    return nil, false
	}
	return o.OrderAsc, true
}

// HasOrderAsc returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasOrderAsc() bool {
	if o != nil && !isNil(o.OrderAsc) {
		return true
	}

	return false
}

// SetOrderAsc gets a reference to the given bool and assigns it to the OrderAsc field.
func (o *RepositoryStatesFilters) SetOrderAsc(v bool) {
	o.OrderAsc = &v
}

// GetIdFilter returns the IdFilter field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetIdFilter() string {
	if o == nil || isNil(o.IdFilter) {
		var ret string
		return ret
	}
	return *o.IdFilter
}

// GetIdFilterOk returns a tuple with the IdFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetIdFilterOk() (*string, bool) {
	if o == nil || isNil(o.IdFilter) {
    return nil, false
	}
	return o.IdFilter, true
}

// HasIdFilter returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasIdFilter() bool {
	if o != nil && !isNil(o.IdFilter) {
		return true
	}

	return false
}

// SetIdFilter gets a reference to the given string and assigns it to the IdFilter field.
func (o *RepositoryStatesFilters) SetIdFilter(v string) {
	o.IdFilter = &v
}

// GetNameFilter returns the NameFilter field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetNameFilter() string {
	if o == nil || isNil(o.NameFilter) {
		var ret string
		return ret
	}
	return *o.NameFilter
}

// GetNameFilterOk returns a tuple with the NameFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetNameFilterOk() (*string, bool) {
	if o == nil || isNil(o.NameFilter) {
    return nil, false
	}
	return o.NameFilter, true
}

// HasNameFilter returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasNameFilter() bool {
	if o != nil && !isNil(o.NameFilter) {
		return true
	}

	return false
}

// SetNameFilter gets a reference to the given string and assigns it to the NameFilter field.
func (o *RepositoryStatesFilters) SetNameFilter(v string) {
	o.NameFilter = &v
}

// GetTypeFilter returns the TypeFilter field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetTypeFilter() ERepositoryType {
	if o == nil || isNil(o.TypeFilter) {
		var ret ERepositoryType
		return ret
	}
	return *o.TypeFilter
}

// GetTypeFilterOk returns a tuple with the TypeFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetTypeFilterOk() (*ERepositoryType, bool) {
	if o == nil || isNil(o.TypeFilter) {
    return nil, false
	}
	return o.TypeFilter, true
}

// HasTypeFilter returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasTypeFilter() bool {
	if o != nil && !isNil(o.TypeFilter) {
		return true
	}

	return false
}

// SetTypeFilter gets a reference to the given ERepositoryType and assigns it to the TypeFilter field.
func (o *RepositoryStatesFilters) SetTypeFilter(v ERepositoryType) {
	o.TypeFilter = &v
}

// GetCapacityFilter returns the CapacityFilter field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetCapacityFilter() float64 {
	if o == nil || isNil(o.CapacityFilter) {
		var ret float64
		return ret
	}
	return *o.CapacityFilter
}

// GetCapacityFilterOk returns a tuple with the CapacityFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetCapacityFilterOk() (*float64, bool) {
	if o == nil || isNil(o.CapacityFilter) {
    return nil, false
	}
	return o.CapacityFilter, true
}

// HasCapacityFilter returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasCapacityFilter() bool {
	if o != nil && !isNil(o.CapacityFilter) {
		return true
	}

	return false
}

// SetCapacityFilter gets a reference to the given float64 and assigns it to the CapacityFilter field.
func (o *RepositoryStatesFilters) SetCapacityFilter(v float64) {
	o.CapacityFilter = &v
}

// GetFreeSpaceFilter returns the FreeSpaceFilter field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetFreeSpaceFilter() float64 {
	if o == nil || isNil(o.FreeSpaceFilter) {
		var ret float64
		return ret
	}
	return *o.FreeSpaceFilter
}

// GetFreeSpaceFilterOk returns a tuple with the FreeSpaceFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetFreeSpaceFilterOk() (*float64, bool) {
	if o == nil || isNil(o.FreeSpaceFilter) {
    return nil, false
	}
	return o.FreeSpaceFilter, true
}

// HasFreeSpaceFilter returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasFreeSpaceFilter() bool {
	if o != nil && !isNil(o.FreeSpaceFilter) {
		return true
	}

	return false
}

// SetFreeSpaceFilter gets a reference to the given float64 and assigns it to the FreeSpaceFilter field.
func (o *RepositoryStatesFilters) SetFreeSpaceFilter(v float64) {
	o.FreeSpaceFilter = &v
}

// GetUsedSpaceFilter returns the UsedSpaceFilter field value if set, zero value otherwise.
func (o *RepositoryStatesFilters) GetUsedSpaceFilter() float64 {
	if o == nil || isNil(o.UsedSpaceFilter) {
		var ret float64
		return ret
	}
	return *o.UsedSpaceFilter
}

// GetUsedSpaceFilterOk returns a tuple with the UsedSpaceFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatesFilters) GetUsedSpaceFilterOk() (*float64, bool) {
	if o == nil || isNil(o.UsedSpaceFilter) {
    return nil, false
	}
	return o.UsedSpaceFilter, true
}

// HasUsedSpaceFilter returns a boolean if a field has been set.
func (o *RepositoryStatesFilters) HasUsedSpaceFilter() bool {
	if o != nil && !isNil(o.UsedSpaceFilter) {
		return true
	}

	return false
}

// SetUsedSpaceFilter gets a reference to the given float64 and assigns it to the UsedSpaceFilter field.
func (o *RepositoryStatesFilters) SetUsedSpaceFilter(v float64) {
	o.UsedSpaceFilter = &v
}

func (o RepositoryStatesFilters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Skip) {
		toSerialize["skip"] = o.Skip
	}
	if !isNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !isNil(o.OrderColumn) {
		toSerialize["orderColumn"] = o.OrderColumn
	}
	if !isNil(o.OrderAsc) {
		toSerialize["orderAsc"] = o.OrderAsc
	}
	if !isNil(o.IdFilter) {
		toSerialize["idFilter"] = o.IdFilter
	}
	if !isNil(o.NameFilter) {
		toSerialize["nameFilter"] = o.NameFilter
	}
	if !isNil(o.TypeFilter) {
		toSerialize["typeFilter"] = o.TypeFilter
	}
	if !isNil(o.CapacityFilter) {
		toSerialize["capacityFilter"] = o.CapacityFilter
	}
	if !isNil(o.FreeSpaceFilter) {
		toSerialize["freeSpaceFilter"] = o.FreeSpaceFilter
	}
	if !isNil(o.UsedSpaceFilter) {
		toSerialize["usedSpaceFilter"] = o.UsedSpaceFilter
	}
	return json.Marshal(toSerialize)
}

type NullableRepositoryStatesFilters struct {
	value *RepositoryStatesFilters
	isSet bool
}

func (v NullableRepositoryStatesFilters) Get() *RepositoryStatesFilters {
	return v.value
}

func (v *NullableRepositoryStatesFilters) Set(val *RepositoryStatesFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryStatesFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryStatesFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryStatesFilters(val *RepositoryStatesFilters) *NullableRepositoryStatesFilters {
	return &NullableRepositoryStatesFilters{value: val, isSet: true}
}

func (v NullableRepositoryStatesFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryStatesFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


