/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EDayNumberInMonth Week day number in the month.
type EDayNumberInMonth string

// List of EDayNumberInMonth
const (
	EDAYNUMBERINMONTH_FIRST EDayNumberInMonth = "First"
	EDAYNUMBERINMONTH_SECOND EDayNumberInMonth = "Second"
	EDAYNUMBERINMONTH_THIRD EDayNumberInMonth = "Third"
	EDAYNUMBERINMONTH_FOURTH EDayNumberInMonth = "Fourth"
	EDAYNUMBERINMONTH_LAST EDayNumberInMonth = "Last"
	EDAYNUMBERINMONTH_ON_DAY EDayNumberInMonth = "OnDay"
)

// All allowed values of EDayNumberInMonth enum
var AllowedEDayNumberInMonthEnumValues = []EDayNumberInMonth{
	"First",
	"Second",
	"Third",
	"Fourth",
	"Last",
	"OnDay",
}

func (v *EDayNumberInMonth) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EDayNumberInMonth(value)
	for _, existing := range AllowedEDayNumberInMonthEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EDayNumberInMonth", value)
}

// NewEDayNumberInMonthFromValue returns a pointer to a valid EDayNumberInMonth
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEDayNumberInMonthFromValue(v string) (*EDayNumberInMonth, error) {
	ev := EDayNumberInMonth(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EDayNumberInMonth: valid values are %v", v, AllowedEDayNumberInMonthEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EDayNumberInMonth) IsValid() bool {
	for _, existing := range AllowedEDayNumberInMonthEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EDayNumberInMonth value
func (v EDayNumberInMonth) Ptr() *EDayNumberInMonth {
	return &v
}

type NullableEDayNumberInMonth struct {
	value *EDayNumberInMonth
	isSet bool
}

func (v NullableEDayNumberInMonth) Get() *EDayNumberInMonth {
	return v.value
}

func (v *NullableEDayNumberInMonth) Set(val *EDayNumberInMonth) {
	v.value = val
	v.isSet = true
}

func (v NullableEDayNumberInMonth) IsSet() bool {
	return v.isSet
}

func (v *NullableEDayNumberInMonth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEDayNumberInMonth(val *EDayNumberInMonth) *NullableEDayNumberInMonth {
	return &NullableEDayNumberInMonth{value: val, isSet: true}
}

func (v NullableEDayNumberInMonth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEDayNumberInMonth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

