/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureComputeCloudCredentialsSubscriptionInfo struct for AzureComputeCloudCredentialsSubscriptionInfo
type AzureComputeCloudCredentialsSubscriptionInfo struct {
	// ID that Veeam Backup & Replication assigned to the Azure subscription.
	Id string `json:"id"`
	// Original Azure subscription ID.
	AzureSubscriptionId string `json:"azureSubscriptionId"`
	// Azure subscription name.
	AzureSubscriptionName *string `json:"azureSubscriptionName,omitempty"`
}

// NewAzureComputeCloudCredentialsSubscriptionInfo instantiates a new AzureComputeCloudCredentialsSubscriptionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureComputeCloudCredentialsSubscriptionInfo(id string, azureSubscriptionId string) *AzureComputeCloudCredentialsSubscriptionInfo {
	this := AzureComputeCloudCredentialsSubscriptionInfo{}
	this.Id = id
	this.AzureSubscriptionId = azureSubscriptionId
	return &this
}

// NewAzureComputeCloudCredentialsSubscriptionInfoWithDefaults instantiates a new AzureComputeCloudCredentialsSubscriptionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureComputeCloudCredentialsSubscriptionInfoWithDefaults() *AzureComputeCloudCredentialsSubscriptionInfo {
	this := AzureComputeCloudCredentialsSubscriptionInfo{}
	return &this
}

// GetId returns the Id field value
func (o *AzureComputeCloudCredentialsSubscriptionInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionInfo) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AzureComputeCloudCredentialsSubscriptionInfo) SetId(v string) {
	o.Id = v
}

// GetAzureSubscriptionId returns the AzureSubscriptionId field value
func (o *AzureComputeCloudCredentialsSubscriptionInfo) GetAzureSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AzureSubscriptionId
}

// GetAzureSubscriptionIdOk returns a tuple with the AzureSubscriptionId field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionInfo) GetAzureSubscriptionIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.AzureSubscriptionId, true
}

// SetAzureSubscriptionId sets field value
func (o *AzureComputeCloudCredentialsSubscriptionInfo) SetAzureSubscriptionId(v string) {
	o.AzureSubscriptionId = v
}

// GetAzureSubscriptionName returns the AzureSubscriptionName field value if set, zero value otherwise.
func (o *AzureComputeCloudCredentialsSubscriptionInfo) GetAzureSubscriptionName() string {
	if o == nil || isNil(o.AzureSubscriptionName) {
		var ret string
		return ret
	}
	return *o.AzureSubscriptionName
}

// GetAzureSubscriptionNameOk returns a tuple with the AzureSubscriptionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionInfo) GetAzureSubscriptionNameOk() (*string, bool) {
	if o == nil || isNil(o.AzureSubscriptionName) {
    return nil, false
	}
	return o.AzureSubscriptionName, true
}

// HasAzureSubscriptionName returns a boolean if a field has been set.
func (o *AzureComputeCloudCredentialsSubscriptionInfo) HasAzureSubscriptionName() bool {
	if o != nil && !isNil(o.AzureSubscriptionName) {
		return true
	}

	return false
}

// SetAzureSubscriptionName gets a reference to the given string and assigns it to the AzureSubscriptionName field.
func (o *AzureComputeCloudCredentialsSubscriptionInfo) SetAzureSubscriptionName(v string) {
	o.AzureSubscriptionName = &v
}

func (o AzureComputeCloudCredentialsSubscriptionInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["azureSubscriptionId"] = o.AzureSubscriptionId
	}
	if !isNil(o.AzureSubscriptionName) {
		toSerialize["azureSubscriptionName"] = o.AzureSubscriptionName
	}
	return json.Marshal(toSerialize)
}

type NullableAzureComputeCloudCredentialsSubscriptionInfo struct {
	value *AzureComputeCloudCredentialsSubscriptionInfo
	isSet bool
}

func (v NullableAzureComputeCloudCredentialsSubscriptionInfo) Get() *AzureComputeCloudCredentialsSubscriptionInfo {
	return v.value
}

func (v *NullableAzureComputeCloudCredentialsSubscriptionInfo) Set(val *AzureComputeCloudCredentialsSubscriptionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureComputeCloudCredentialsSubscriptionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureComputeCloudCredentialsSubscriptionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureComputeCloudCredentialsSubscriptionInfo(val *AzureComputeCloudCredentialsSubscriptionInfo) *NullableAzureComputeCloudCredentialsSubscriptionInfo {
	return &NullableAzureComputeCloudCredentialsSubscriptionInfo{value: val, isSet: true}
}

func (v NullableAzureComputeCloudCredentialsSubscriptionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureComputeCloudCredentialsSubscriptionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


