/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// LinuxLocalStorageSpec Linux-based repository.
type LinuxLocalStorageSpec struct {
	RepositorySpec
	// ID of the server that is used as a backup repository.
	HostId string `json:"hostId"`
	Repository LinuxLocalRepositorySettingsModel `json:"repository"`
	MountServer MountServerSettingsModel `json:"mountServer"`
}

// NewLinuxLocalStorageSpec instantiates a new LinuxLocalStorageSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinuxLocalStorageSpec(hostId string, repository LinuxLocalRepositorySettingsModel, mountServer MountServerSettingsModel, name string, description string, type_ ERepositoryType) *LinuxLocalStorageSpec {
	this := LinuxLocalStorageSpec{}
	this.Name = name
	this.Description = description
	this.Type = type_
	this.HostId = hostId
	this.Repository = repository
	this.MountServer = mountServer
	return &this
}

// NewLinuxLocalStorageSpecWithDefaults instantiates a new LinuxLocalStorageSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinuxLocalStorageSpecWithDefaults() *LinuxLocalStorageSpec {
	this := LinuxLocalStorageSpec{}
	return &this
}

// GetHostId returns the HostId field value
func (o *LinuxLocalStorageSpec) GetHostId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value
// and a boolean to check if the value has been set.
func (o *LinuxLocalStorageSpec) GetHostIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.HostId, true
}

// SetHostId sets field value
func (o *LinuxLocalStorageSpec) SetHostId(v string) {
	o.HostId = v
}

// GetRepository returns the Repository field value
func (o *LinuxLocalStorageSpec) GetRepository() LinuxLocalRepositorySettingsModel {
	if o == nil {
		var ret LinuxLocalRepositorySettingsModel
		return ret
	}

	return o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value
// and a boolean to check if the value has been set.
func (o *LinuxLocalStorageSpec) GetRepositoryOk() (*LinuxLocalRepositorySettingsModel, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Repository, true
}

// SetRepository sets field value
func (o *LinuxLocalStorageSpec) SetRepository(v LinuxLocalRepositorySettingsModel) {
	o.Repository = v
}

// GetMountServer returns the MountServer field value
func (o *LinuxLocalStorageSpec) GetMountServer() MountServerSettingsModel {
	if o == nil {
		var ret MountServerSettingsModel
		return ret
	}

	return o.MountServer
}

// GetMountServerOk returns a tuple with the MountServer field value
// and a boolean to check if the value has been set.
func (o *LinuxLocalStorageSpec) GetMountServerOk() (*MountServerSettingsModel, bool) {
	if o == nil {
    return nil, false
	}
	return &o.MountServer, true
}

// SetMountServer sets field value
func (o *LinuxLocalStorageSpec) SetMountServer(v MountServerSettingsModel) {
	o.MountServer = v
}

func (o LinuxLocalStorageSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedRepositorySpec, errRepositorySpec := json.Marshal(o.RepositorySpec)
	if errRepositorySpec != nil {
		return []byte{}, errRepositorySpec
	}
	errRepositorySpec = json.Unmarshal([]byte(serializedRepositorySpec), &toSerialize)
	if errRepositorySpec != nil {
		return []byte{}, errRepositorySpec
	}
	if true {
		toSerialize["hostId"] = o.HostId
	}
	if true {
		toSerialize["repository"] = o.Repository
	}
	if true {
		toSerialize["mountServer"] = o.MountServer
	}
	return json.Marshal(toSerialize)
}

type NullableLinuxLocalStorageSpec struct {
	value *LinuxLocalStorageSpec
	isSet bool
}

func (v NullableLinuxLocalStorageSpec) Get() *LinuxLocalStorageSpec {
	return v.value
}

func (v *NullableLinuxLocalStorageSpec) Set(val *LinuxLocalStorageSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableLinuxLocalStorageSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableLinuxLocalStorageSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinuxLocalStorageSpec(val *LinuxLocalStorageSpec) *NullableLinuxLocalStorageSpec {
	return &NullableLinuxLocalStorageSpec{value: val, isSet: true}
}

func (v NullableLinuxLocalStorageSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinuxLocalStorageSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


