/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev1
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BackupJobImportProxiesModel Backup proxies.
type BackupJobImportProxiesModel struct {
	// If *true*, backup proxies are detected and assigned automatically.
	AutomaticSelection bool `json:"automaticSelection"`
	// Array of backup proxies.
	Proxies *[]BackupProxyImportModel `json:"proxies,omitempty"`
}

// NewBackupJobImportProxiesModel instantiates a new BackupJobImportProxiesModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupJobImportProxiesModel(automaticSelection bool) *BackupJobImportProxiesModel {
	this := BackupJobImportProxiesModel{}
	this.AutomaticSelection = automaticSelection
	return &this
}

// NewBackupJobImportProxiesModelWithDefaults instantiates a new BackupJobImportProxiesModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupJobImportProxiesModelWithDefaults() *BackupJobImportProxiesModel {
	this := BackupJobImportProxiesModel{}
	var automaticSelection bool = true
	this.AutomaticSelection = automaticSelection
	return &this
}

// GetAutomaticSelection returns the AutomaticSelection field value
func (o *BackupJobImportProxiesModel) GetAutomaticSelection() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutomaticSelection
}

// GetAutomaticSelectionOk returns a tuple with the AutomaticSelection field value
// and a boolean to check if the value has been set.
func (o *BackupJobImportProxiesModel) GetAutomaticSelectionOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AutomaticSelection, true
}

// SetAutomaticSelection sets field value
func (o *BackupJobImportProxiesModel) SetAutomaticSelection(v bool) {
	o.AutomaticSelection = v
}

// GetProxies returns the Proxies field value if set, zero value otherwise.
func (o *BackupJobImportProxiesModel) GetProxies() []BackupProxyImportModel {
	if o == nil || o.Proxies == nil {
		var ret []BackupProxyImportModel
		return ret
	}
	return *o.Proxies
}

// GetProxiesOk returns a tuple with the Proxies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupJobImportProxiesModel) GetProxiesOk() (*[]BackupProxyImportModel, bool) {
	if o == nil || o.Proxies == nil {
		return nil, false
	}
	return o.Proxies, true
}

// HasProxies returns a boolean if a field has been set.
func (o *BackupJobImportProxiesModel) HasProxies() bool {
	if o != nil && o.Proxies != nil {
		return true
	}

	return false
}

// SetProxies gets a reference to the given []BackupProxyImportModel and assigns it to the Proxies field.
func (o *BackupJobImportProxiesModel) SetProxies(v []BackupProxyImportModel) {
	o.Proxies = &v
}

func (o BackupJobImportProxiesModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["automaticSelection"] = o.AutomaticSelection
	}
	if o.Proxies != nil {
		toSerialize["proxies"] = o.Proxies
	}
	return json.Marshal(toSerialize)
}

type NullableBackupJobImportProxiesModel struct {
	value *BackupJobImportProxiesModel
	isSet bool
}

func (v NullableBackupJobImportProxiesModel) Get() *BackupJobImportProxiesModel {
	return v.value
}

func (v *NullableBackupJobImportProxiesModel) Set(val *BackupJobImportProxiesModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupJobImportProxiesModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupJobImportProxiesModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupJobImportProxiesModel(val *BackupJobImportProxiesModel) *NullableBackupJobImportProxiesModel {
	return &NullableBackupJobImportProxiesModel{value: val, isSet: true}
}

func (v NullableBackupJobImportProxiesModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupJobImportProxiesModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


