/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev2
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ProxyModel struct for ProxyModel
type ProxyModel struct {
	// ID of the backup proxy.
	Id string `json:"id"`
	// Name of the backup proxy.
	Name string `json:"name"`
	// Description of the backup proxy.
	Description string `json:"description"`
	Type EProxyType `json:"type"`
}

// NewProxyModel instantiates a new ProxyModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxyModel(id string, name string, description string, type_ EProxyType, ) *ProxyModel {
	this := ProxyModel{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Type = type_
	return &this
}

// NewProxyModelWithDefaults instantiates a new ProxyModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxyModelWithDefaults() *ProxyModel {
	this := ProxyModel{}
	return &this
}

// GetId returns the Id field value
func (o *ProxyModel) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProxyModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProxyModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ProxyModel) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProxyModel) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProxyModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ProxyModel) GetDescription() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProxyModel) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProxyModel) SetDescription(v string) {
	o.Description = v
}

// GetType returns the Type field value
func (o *ProxyModel) GetType() EProxyType {
	if o == nil  {
		var ret EProxyType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProxyModel) GetTypeOk() (*EProxyType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProxyModel) SetType(v EProxyType) {
	o.Type = v
}

func (o ProxyModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableProxyModel struct {
	value *ProxyModel
	isSet bool
}

func (v NullableProxyModel) Get() *ProxyModel {
	return v.value
}

func (v *NullableProxyModel) Set(val *ProxyModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProxyModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProxyModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxyModel(val *ProxyModel) *NullableProxyModel {
	return &NullableProxyModel{value: val, isSet: true}
}

func (v NullableProxyModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxyModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


