/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev2
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EJobStatus Current status of the job.
type EJobStatus string

// List of EJobStatus
const (
	EJOBSTATUS_RUNNING EJobStatus = "running"
	EJOBSTATUS_INACTIVE EJobStatus = "inactive"
	EJOBSTATUS_DISABLED EJobStatus = "disabled"
)

func (v *EJobStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EJobStatus(value)
	for _, existing := range []EJobStatus{ "running", "inactive", "disabled",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EJobStatus", value)
}

// Ptr returns reference to EJobStatus value
func (v EJobStatus) Ptr() *EJobStatus {
	return &v
}

type NullableEJobStatus struct {
	value *EJobStatus
	isSet bool
}

func (v NullableEJobStatus) Get() *EJobStatus {
	return v.value
}

func (v *NullableEJobStatus) Set(val *EJobStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableEJobStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableEJobStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEJobStatus(val *EJobStatus) *NullableEJobStatus {
	return &NullableEJobStatus{value: val, isSet: true}
}

func (v NullableEJobStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEJobStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

