/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// JobModel - struct for JobModel
type JobModel struct {
	BackupJobModel *BackupJobModel
}

// BackupJobModelAsJobModel is a convenience function that returns BackupJobModel wrapped in JobModel
func BackupJobModelAsJobModel(v *BackupJobModel) JobModel {
	return JobModel{
		BackupJobModel: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *JobModel) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BackupJobModel
	err = newStrictDecoder(data).Decode(&dst.BackupJobModel)
	if err == nil {
		jsonBackupJobModel, _ := json.Marshal(dst.BackupJobModel)
		if string(jsonBackupJobModel) == "{}" { // empty struct
			dst.BackupJobModel = nil
		} else {
			match++
		}
	} else {
		dst.BackupJobModel = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BackupJobModel = nil

		return fmt.Errorf("data matches more than one schema in oneOf(JobModel)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(JobModel)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src JobModel) MarshalJSON() ([]byte, error) {
	if src.BackupJobModel != nil {
		return json.Marshal(&src.BackupJobModel)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *JobModel) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BackupJobModel != nil {
		return obj.BackupJobModel
	}

	// all schemas are nil
	return nil
}

type NullableJobModel struct {
	value *JobModel
	isSet bool
}

func (v NullableJobModel) Get() *JobModel {
	return v.value
}

func (v *NullableJobModel) Set(val *JobModel) {
	v.value = val
	v.isSet = true
}

func (v NullableJobModel) IsSet() bool {
	return v.isSet
}

func (v *NullableJobModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobModel(val *JobModel) *NullableJobModel {
	return &NullableJobModel{value: val, isSet: true}
}

func (v NullableJobModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


