/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CapacityExtentModel struct for CapacityExtentModel
type CapacityExtentModel struct {
	// ID of an object storage repository added as a capacity extent.
	Id string `json:"id"`
}

// NewCapacityExtentModel instantiates a new CapacityExtentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapacityExtentModel(id string) *CapacityExtentModel {
	this := CapacityExtentModel{}
	this.Id = id
	return &this
}

// NewCapacityExtentModelWithDefaults instantiates a new CapacityExtentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapacityExtentModelWithDefaults() *CapacityExtentModel {
	this := CapacityExtentModel{}
	return &this
}

// GetId returns the Id field value
func (o *CapacityExtentModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CapacityExtentModel) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CapacityExtentModel) SetId(v string) {
	o.Id = v
}

func (o CapacityExtentModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableCapacityExtentModel struct {
	value *CapacityExtentModel
	isSet bool
}

func (v NullableCapacityExtentModel) Get() *CapacityExtentModel {
	return v.value
}

func (v *NullableCapacityExtentModel) Set(val *CapacityExtentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCapacityExtentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCapacityExtentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapacityExtentModel(val *CapacityExtentModel) *NullableCapacityExtentModel {
	return &NullableCapacityExtentModel{value: val, isSet: true}
}

func (v NullableCapacityExtentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapacityExtentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


