/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CloudDeviceCodeModel struct for CloudDeviceCodeModel
type CloudDeviceCodeModel struct {
	Type ECloudCredentialsType `json:"type"`
}

// NewCloudDeviceCodeModel instantiates a new CloudDeviceCodeModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudDeviceCodeModel(type_ ECloudCredentialsType) *CloudDeviceCodeModel {
	this := CloudDeviceCodeModel{}
	this.Type = type_
	return &this
}

// NewCloudDeviceCodeModelWithDefaults instantiates a new CloudDeviceCodeModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudDeviceCodeModelWithDefaults() *CloudDeviceCodeModel {
	this := CloudDeviceCodeModel{}
	return &this
}

// GetType returns the Type field value
func (o *CloudDeviceCodeModel) GetType() ECloudCredentialsType {
	if o == nil {
		var ret ECloudCredentialsType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CloudDeviceCodeModel) GetTypeOk() (*ECloudCredentialsType, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CloudDeviceCodeModel) SetType(v ECloudCredentialsType) {
	o.Type = v
}

func (o CloudDeviceCodeModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableCloudDeviceCodeModel struct {
	value *CloudDeviceCodeModel
	isSet bool
}

func (v NullableCloudDeviceCodeModel) Get() *CloudDeviceCodeModel {
	return v.value
}

func (v *NullableCloudDeviceCodeModel) Set(val *CloudDeviceCodeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudDeviceCodeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudDeviceCodeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudDeviceCodeModel(val *CloudDeviceCodeModel) *NullableCloudDeviceCodeModel {
	return &NullableCloudDeviceCodeModel{value: val, isSet: true}
}

func (v NullableCloudDeviceCodeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudDeviceCodeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


