/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br> Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic. 
 *
 * API version: 1.0-rev2
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// FullBackupMaintenanceRemoveDataModel Backup data setting for deleted VMs.
type FullBackupMaintenanceRemoveDataModel struct {
	// If *true*, Veeam Backup & Replication keeps the backup data of deleted VMs for the `afterDays` number of days.
	IsEnabled bool `json:"isEnabled"`
	// Number of days.
	AfterDays *int32 `json:"afterDays,omitempty"`
}

// NewFullBackupMaintenanceRemoveDataModel instantiates a new FullBackupMaintenanceRemoveDataModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFullBackupMaintenanceRemoveDataModel(isEnabled bool, ) *FullBackupMaintenanceRemoveDataModel {
	this := FullBackupMaintenanceRemoveDataModel{}
	this.IsEnabled = isEnabled
	return &this
}

// NewFullBackupMaintenanceRemoveDataModelWithDefaults instantiates a new FullBackupMaintenanceRemoveDataModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFullBackupMaintenanceRemoveDataModelWithDefaults() *FullBackupMaintenanceRemoveDataModel {
	this := FullBackupMaintenanceRemoveDataModel{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value
func (o *FullBackupMaintenanceRemoveDataModel) GetIsEnabled() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *FullBackupMaintenanceRemoveDataModel) GetIsEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *FullBackupMaintenanceRemoveDataModel) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetAfterDays returns the AfterDays field value if set, zero value otherwise.
func (o *FullBackupMaintenanceRemoveDataModel) GetAfterDays() int32 {
	if o == nil || o.AfterDays == nil {
		var ret int32
		return ret
	}
	return *o.AfterDays
}

// GetAfterDaysOk returns a tuple with the AfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FullBackupMaintenanceRemoveDataModel) GetAfterDaysOk() (*int32, bool) {
	if o == nil || o.AfterDays == nil {
		return nil, false
	}
	return o.AfterDays, true
}

// HasAfterDays returns a boolean if a field has been set.
func (o *FullBackupMaintenanceRemoveDataModel) HasAfterDays() bool {
	if o != nil && o.AfterDays != nil {
		return true
	}

	return false
}

// SetAfterDays gets a reference to the given int32 and assigns it to the AfterDays field.
func (o *FullBackupMaintenanceRemoveDataModel) SetAfterDays(v int32) {
	o.AfterDays = &v
}

func (o FullBackupMaintenanceRemoveDataModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	if o.AfterDays != nil {
		toSerialize["afterDays"] = o.AfterDays
	}
	return json.Marshal(toSerialize)
}

type NullableFullBackupMaintenanceRemoveDataModel struct {
	value *FullBackupMaintenanceRemoveDataModel
	isSet bool
}

func (v NullableFullBackupMaintenanceRemoveDataModel) Get() *FullBackupMaintenanceRemoveDataModel {
	return v.value
}

func (v *NullableFullBackupMaintenanceRemoveDataModel) Set(val *FullBackupMaintenanceRemoveDataModel) {
	v.value = val
	v.isSet = true
}

func (v NullableFullBackupMaintenanceRemoveDataModel) IsSet() bool {
	return v.isSet
}

func (v *NullableFullBackupMaintenanceRemoveDataModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFullBackupMaintenanceRemoveDataModel(val *FullBackupMaintenanceRemoveDataModel) *NullableFullBackupMaintenanceRemoveDataModel {
	return &NullableFullBackupMaintenanceRemoveDataModel{value: val, isSet: true}
}

func (v NullableFullBackupMaintenanceRemoveDataModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFullBackupMaintenanceRemoveDataModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


