/*
Veeam Backup & Replication REST API

This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br> Some request and response bodies refer to reusable schema objects that are defined in the `schemas` section of the REST API specification. Schemas, in turn, may inherit a part of their properties by referring to other schemas, and be polymorphic by referring to multiple alternate schemas.

API version: 1.1-rev0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// CredentialsSpec - struct for CredentialsSpec
type CredentialsSpec struct {
	LinuxCredentialsSpec *LinuxCredentialsSpec
	StandardCredentialsSpec *StandardCredentialsSpec
}

// LinuxCredentialsSpecAsCredentialsSpec is a convenience function that returns LinuxCredentialsSpec wrapped in CredentialsSpec
func LinuxCredentialsSpecAsCredentialsSpec(v *LinuxCredentialsSpec) CredentialsSpec {
	return CredentialsSpec{
		LinuxCredentialsSpec: v,
	}
}

// StandardCredentialsSpecAsCredentialsSpec is a convenience function that returns StandardCredentialsSpec wrapped in CredentialsSpec
func StandardCredentialsSpecAsCredentialsSpec(v *StandardCredentialsSpec) CredentialsSpec {
	return CredentialsSpec{
		StandardCredentialsSpec: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CredentialsSpec) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into LinuxCredentialsSpec
	err = newStrictDecoder(data).Decode(&dst.LinuxCredentialsSpec)
	if err == nil {
		jsonLinuxCredentialsSpec, _ := json.Marshal(dst.LinuxCredentialsSpec)
		if string(jsonLinuxCredentialsSpec) == "{}" { // empty struct
			dst.LinuxCredentialsSpec = nil
		} else {
			match++
		}
	} else {
		dst.LinuxCredentialsSpec = nil
	}

	// try to unmarshal data into StandardCredentialsSpec
	err = newStrictDecoder(data).Decode(&dst.StandardCredentialsSpec)
	if err == nil {
		jsonStandardCredentialsSpec, _ := json.Marshal(dst.StandardCredentialsSpec)
		if string(jsonStandardCredentialsSpec) == "{}" { // empty struct
			dst.StandardCredentialsSpec = nil
		} else {
			match++
		}
	} else {
		dst.StandardCredentialsSpec = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.LinuxCredentialsSpec = nil
		dst.StandardCredentialsSpec = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CredentialsSpec)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CredentialsSpec)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CredentialsSpec) MarshalJSON() ([]byte, error) {
	if src.LinuxCredentialsSpec != nil {
		return json.Marshal(&src.LinuxCredentialsSpec)
	}

	if src.StandardCredentialsSpec != nil {
		return json.Marshal(&src.StandardCredentialsSpec)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CredentialsSpec) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.LinuxCredentialsSpec != nil {
		return obj.LinuxCredentialsSpec
	}

	if obj.StandardCredentialsSpec != nil {
		return obj.StandardCredentialsSpec
	}

	// all schemas are nil
	return nil
}

type NullableCredentialsSpec struct {
	value *CredentialsSpec
	isSet bool
}

func (v NullableCredentialsSpec) Get() *CredentialsSpec {
	return v.value
}

func (v *NullableCredentialsSpec) Set(val *CredentialsSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsSpec(val *CredentialsSpec) *NullableCredentialsSpec {
	return &NullableCredentialsSpec{value: val, isSet: true}
}

func (v NullableCredentialsSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


