// Code generated by go-swagger; DO NOT EDIT.

package backup_objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/veeamhub/veeam-vbr-sdk-go/models"
)

// GetBackupObjectRestorePointsReader is a Reader for the GetBackupObjectRestorePoints structure.
type GetBackupObjectRestorePointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBackupObjectRestorePointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBackupObjectRestorePointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBackupObjectRestorePointsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetBackupObjectRestorePointsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBackupObjectRestorePointsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBackupObjectRestorePointsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBackupObjectRestorePointsOK creates a GetBackupObjectRestorePointsOK with default headers values
func NewGetBackupObjectRestorePointsOK() *GetBackupObjectRestorePointsOK {
	return &GetBackupObjectRestorePointsOK{}
}

/* GetBackupObjectRestorePointsOK describes a response with status code 200, with default header values.

OK
*/
type GetBackupObjectRestorePointsOK struct {
	Payload *models.ObjectRestorePointsResult
}

func (o *GetBackupObjectRestorePointsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupObjects/{id}/restorePoints][%d] getBackupObjectRestorePointsOK  %+v", 200, o.Payload)
}
func (o *GetBackupObjectRestorePointsOK) GetPayload() *models.ObjectRestorePointsResult {
	return o.Payload
}

func (o *GetBackupObjectRestorePointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ObjectRestorePointsResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupObjectRestorePointsUnauthorized creates a GetBackupObjectRestorePointsUnauthorized with default headers values
func NewGetBackupObjectRestorePointsUnauthorized() *GetBackupObjectRestorePointsUnauthorized {
	return &GetBackupObjectRestorePointsUnauthorized{}
}

/* GetBackupObjectRestorePointsUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The authorization header has been expected but not found (or found but is expired).
*/
type GetBackupObjectRestorePointsUnauthorized struct {
	Payload *models.Error
}

func (o *GetBackupObjectRestorePointsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupObjects/{id}/restorePoints][%d] getBackupObjectRestorePointsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetBackupObjectRestorePointsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupObjectRestorePointsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupObjectRestorePointsForbidden creates a GetBackupObjectRestorePointsForbidden with default headers values
func NewGetBackupObjectRestorePointsForbidden() *GetBackupObjectRestorePointsForbidden {
	return &GetBackupObjectRestorePointsForbidden{}
}

/* GetBackupObjectRestorePointsForbidden describes a response with status code 403, with default header values.

Forbidden. The user sending the request does not have adequate privileges to access one or more objects specified in the request.
*/
type GetBackupObjectRestorePointsForbidden struct {
	Payload *models.Error
}

func (o *GetBackupObjectRestorePointsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupObjects/{id}/restorePoints][%d] getBackupObjectRestorePointsForbidden  %+v", 403, o.Payload)
}
func (o *GetBackupObjectRestorePointsForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupObjectRestorePointsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupObjectRestorePointsNotFound creates a GetBackupObjectRestorePointsNotFound with default headers values
func NewGetBackupObjectRestorePointsNotFound() *GetBackupObjectRestorePointsNotFound {
	return &GetBackupObjectRestorePointsNotFound{}
}

/* GetBackupObjectRestorePointsNotFound describes a response with status code 404, with default header values.

Not found. No object was found with the path parameter specified in the request.
*/
type GetBackupObjectRestorePointsNotFound struct {
	Payload *models.Error
}

func (o *GetBackupObjectRestorePointsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupObjects/{id}/restorePoints][%d] getBackupObjectRestorePointsNotFound  %+v", 404, o.Payload)
}
func (o *GetBackupObjectRestorePointsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupObjectRestorePointsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupObjectRestorePointsInternalServerError creates a GetBackupObjectRestorePointsInternalServerError with default headers values
func NewGetBackupObjectRestorePointsInternalServerError() *GetBackupObjectRestorePointsInternalServerError {
	return &GetBackupObjectRestorePointsInternalServerError{}
}

/* GetBackupObjectRestorePointsInternalServerError describes a response with status code 500, with default header values.

Internal server error. The request has been received but could not be completed because of an internal error at the server side.
*/
type GetBackupObjectRestorePointsInternalServerError struct {
	Payload *models.Error
}

func (o *GetBackupObjectRestorePointsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupObjects/{id}/restorePoints][%d] getBackupObjectRestorePointsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBackupObjectRestorePointsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupObjectRestorePointsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
