// Code generated by go-swagger; DO NOT EDIT.

package managed_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllManagedServersParams creates a new GetAllManagedServersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllManagedServersParams() *GetAllManagedServersParams {
	return &GetAllManagedServersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllManagedServersParamsWithTimeout creates a new GetAllManagedServersParams object
// with the ability to set a timeout on a request.
func NewGetAllManagedServersParamsWithTimeout(timeout time.Duration) *GetAllManagedServersParams {
	return &GetAllManagedServersParams{
		timeout: timeout,
	}
}

// NewGetAllManagedServersParamsWithContext creates a new GetAllManagedServersParams object
// with the ability to set a context for a request.
func NewGetAllManagedServersParamsWithContext(ctx context.Context) *GetAllManagedServersParams {
	return &GetAllManagedServersParams{
		Context: ctx,
	}
}

// NewGetAllManagedServersParamsWithHTTPClient creates a new GetAllManagedServersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllManagedServersParamsWithHTTPClient(client *http.Client) *GetAllManagedServersParams {
	return &GetAllManagedServersParams{
		HTTPClient: client,
	}
}

/* GetAllManagedServersParams contains all the parameters to send to the API endpoint
   for the get all managed servers operation.

   Typically these are written to a http.Request.
*/
type GetAllManagedServersParams struct {

	/* Limit.

	   Maximum number of servers to return.

	   Format: int32
	*/
	Limit *int32

	/* NameFilter.

	   Filters servers by the `nameFilter` pattern. The pattern can match any server parameter. To substitute one or more characters, use the asterisk (*) character at the beginning and/or at the end.
	*/
	NameFilter *string

	/* OrderAsc.

	   Sorts servers in the ascending order by the `orderColumn` parameter.
	*/
	OrderAsc *bool

	/* OrderColumn.

	   Sorts servers by one of the server parameters.
	*/
	OrderColumn *string

	/* Skip.

	   Number of servers to skip.

	   Format: int32
	*/
	Skip *int32

	/* TypeFilter.

	   Filters servers by server type.
	*/
	TypeFilter *string

	/* ViTypeFilter.

	   Filters servers by the type of VMware vSphere server.
	*/
	ViTypeFilter *string

	/* XAPIVersion.

	     Version and revision of the client REST API. Must be in the following
	format: *\<version\>-\<revision\>*.


	     Default: "1.0-rev1"
	*/
	XAPIVersion string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all managed servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllManagedServersParams) WithDefaults() *GetAllManagedServersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all managed servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllManagedServersParams) SetDefaults() {
	var (
		xAPIVersionDefault = string("1.0-rev1")
	)

	val := GetAllManagedServersParams{
		XAPIVersion: xAPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get all managed servers params
func (o *GetAllManagedServersParams) WithTimeout(timeout time.Duration) *GetAllManagedServersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all managed servers params
func (o *GetAllManagedServersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all managed servers params
func (o *GetAllManagedServersParams) WithContext(ctx context.Context) *GetAllManagedServersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all managed servers params
func (o *GetAllManagedServersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all managed servers params
func (o *GetAllManagedServersParams) WithHTTPClient(client *http.Client) *GetAllManagedServersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all managed servers params
func (o *GetAllManagedServersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get all managed servers params
func (o *GetAllManagedServersParams) WithLimit(limit *int32) *GetAllManagedServersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get all managed servers params
func (o *GetAllManagedServersParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithNameFilter adds the nameFilter to the get all managed servers params
func (o *GetAllManagedServersParams) WithNameFilter(nameFilter *string) *GetAllManagedServersParams {
	o.SetNameFilter(nameFilter)
	return o
}

// SetNameFilter adds the nameFilter to the get all managed servers params
func (o *GetAllManagedServersParams) SetNameFilter(nameFilter *string) {
	o.NameFilter = nameFilter
}

// WithOrderAsc adds the orderAsc to the get all managed servers params
func (o *GetAllManagedServersParams) WithOrderAsc(orderAsc *bool) *GetAllManagedServersParams {
	o.SetOrderAsc(orderAsc)
	return o
}

// SetOrderAsc adds the orderAsc to the get all managed servers params
func (o *GetAllManagedServersParams) SetOrderAsc(orderAsc *bool) {
	o.OrderAsc = orderAsc
}

// WithOrderColumn adds the orderColumn to the get all managed servers params
func (o *GetAllManagedServersParams) WithOrderColumn(orderColumn *string) *GetAllManagedServersParams {
	o.SetOrderColumn(orderColumn)
	return o
}

// SetOrderColumn adds the orderColumn to the get all managed servers params
func (o *GetAllManagedServersParams) SetOrderColumn(orderColumn *string) {
	o.OrderColumn = orderColumn
}

// WithSkip adds the skip to the get all managed servers params
func (o *GetAllManagedServersParams) WithSkip(skip *int32) *GetAllManagedServersParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the get all managed servers params
func (o *GetAllManagedServersParams) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithTypeFilter adds the typeFilter to the get all managed servers params
func (o *GetAllManagedServersParams) WithTypeFilter(typeFilter *string) *GetAllManagedServersParams {
	o.SetTypeFilter(typeFilter)
	return o
}

// SetTypeFilter adds the typeFilter to the get all managed servers params
func (o *GetAllManagedServersParams) SetTypeFilter(typeFilter *string) {
	o.TypeFilter = typeFilter
}

// WithViTypeFilter adds the viTypeFilter to the get all managed servers params
func (o *GetAllManagedServersParams) WithViTypeFilter(viTypeFilter *string) *GetAllManagedServersParams {
	o.SetViTypeFilter(viTypeFilter)
	return o
}

// SetViTypeFilter adds the viTypeFilter to the get all managed servers params
func (o *GetAllManagedServersParams) SetViTypeFilter(viTypeFilter *string) {
	o.ViTypeFilter = viTypeFilter
}

// WithXAPIVersion adds the xAPIVersion to the get all managed servers params
func (o *GetAllManagedServersParams) WithXAPIVersion(xAPIVersion string) *GetAllManagedServersParams {
	o.SetXAPIVersion(xAPIVersion)
	return o
}

// SetXAPIVersion adds the xApiVersion to the get all managed servers params
func (o *GetAllManagedServersParams) SetXAPIVersion(xAPIVersion string) {
	o.XAPIVersion = xAPIVersion
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllManagedServersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.NameFilter != nil {

		// query param nameFilter
		var qrNameFilter string

		if o.NameFilter != nil {
			qrNameFilter = *o.NameFilter
		}
		qNameFilter := qrNameFilter
		if qNameFilter != "" {

			if err := r.SetQueryParam("nameFilter", qNameFilter); err != nil {
				return err
			}
		}
	}

	if o.OrderAsc != nil {

		// query param orderAsc
		var qrOrderAsc bool

		if o.OrderAsc != nil {
			qrOrderAsc = *o.OrderAsc
		}
		qOrderAsc := swag.FormatBool(qrOrderAsc)
		if qOrderAsc != "" {

			if err := r.SetQueryParam("orderAsc", qOrderAsc); err != nil {
				return err
			}
		}
	}

	if o.OrderColumn != nil {

		// query param orderColumn
		var qrOrderColumn string

		if o.OrderColumn != nil {
			qrOrderColumn = *o.OrderColumn
		}
		qOrderColumn := qrOrderColumn
		if qOrderColumn != "" {

			if err := r.SetQueryParam("orderColumn", qOrderColumn); err != nil {
				return err
			}
		}
	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int32

		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {

			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}
	}

	if o.TypeFilter != nil {

		// query param typeFilter
		var qrTypeFilter string

		if o.TypeFilter != nil {
			qrTypeFilter = *o.TypeFilter
		}
		qTypeFilter := qrTypeFilter
		if qTypeFilter != "" {

			if err := r.SetQueryParam("typeFilter", qTypeFilter); err != nil {
				return err
			}
		}
	}

	if o.ViTypeFilter != nil {

		// query param viTypeFilter
		var qrViTypeFilter string

		if o.ViTypeFilter != nil {
			qrViTypeFilter = *o.ViTypeFilter
		}
		qViTypeFilter := qrViTypeFilter
		if qViTypeFilter != "" {

			if err := r.SetQueryParam("viTypeFilter", qViTypeFilter); err != nil {
				return err
			}
		}
	}

	// header param x-api-version
	if err := r.SetHeaderParam("x-api-version", o.XAPIVersion); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
