// Code generated by go-swagger; DO NOT EDIT.

package automation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/veeamhub/veeam-vbr-sdk-go/models"
)

// NewExportCredentialsParams creates a new ExportCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportCredentialsParams() *ExportCredentialsParams {
	return &ExportCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportCredentialsParamsWithTimeout creates a new ExportCredentialsParams object
// with the ability to set a timeout on a request.
func NewExportCredentialsParamsWithTimeout(timeout time.Duration) *ExportCredentialsParams {
	return &ExportCredentialsParams{
		timeout: timeout,
	}
}

// NewExportCredentialsParamsWithContext creates a new ExportCredentialsParams object
// with the ability to set a context for a request.
func NewExportCredentialsParamsWithContext(ctx context.Context) *ExportCredentialsParams {
	return &ExportCredentialsParams{
		Context: ctx,
	}
}

// NewExportCredentialsParamsWithHTTPClient creates a new ExportCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportCredentialsParamsWithHTTPClient(client *http.Client) *ExportCredentialsParams {
	return &ExportCredentialsParams{
		HTTPClient: client,
	}
}

/* ExportCredentialsParams contains all the parameters to send to the API endpoint
   for the export credentials operation.

   Typically these are written to a http.Request.
*/
type ExportCredentialsParams struct {

	// Body.
	Body *models.CredentialsExportSpec

	/* XAPIVersion.

	     Version and revision of the client REST API. Must be in the following
	format: *\<version\>-\<revision\>*.


	     Default: "1.0-rev1"
	*/
	XAPIVersion string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportCredentialsParams) WithDefaults() *ExportCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportCredentialsParams) SetDefaults() {
	var (
		xAPIVersionDefault = string("1.0-rev1")
	)

	val := ExportCredentialsParams{
		XAPIVersion: xAPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the export credentials params
func (o *ExportCredentialsParams) WithTimeout(timeout time.Duration) *ExportCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export credentials params
func (o *ExportCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export credentials params
func (o *ExportCredentialsParams) WithContext(ctx context.Context) *ExportCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export credentials params
func (o *ExportCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export credentials params
func (o *ExportCredentialsParams) WithHTTPClient(client *http.Client) *ExportCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export credentials params
func (o *ExportCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the export credentials params
func (o *ExportCredentialsParams) WithBody(body *models.CredentialsExportSpec) *ExportCredentialsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the export credentials params
func (o *ExportCredentialsParams) SetBody(body *models.CredentialsExportSpec) {
	o.Body = body
}

// WithXAPIVersion adds the xAPIVersion to the export credentials params
func (o *ExportCredentialsParams) WithXAPIVersion(xAPIVersion string) *ExportCredentialsParams {
	o.SetXAPIVersion(xAPIVersion)
	return o
}

// SetXAPIVersion adds the xApiVersion to the export credentials params
func (o *ExportCredentialsParams) SetXAPIVersion(xAPIVersion string) {
	o.XAPIVersion = xAPIVersion
}

// WriteToRequest writes these params to a swagger request
func (o *ExportCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param x-api-version
	if err := r.SetHeaderParam("x-api-version", o.XAPIVersion); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
