// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/veeamhub/veeam-vbr-sdk-go/models"
)

// DisableJobReader is a Reader for the DisableJob structure.
type DisableJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisableJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDisableJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDisableJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDisableJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDisableJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDisableJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDisableJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDisableJobOK creates a DisableJobOK with default headers values
func NewDisableJobOK() *DisableJobOK {
	return &DisableJobOK{}
}

/* DisableJobOK describes a response with status code 200, with default header values.

Job has been disabled.
*/
type DisableJobOK struct {
	Payload models.EmptySuccessResponse
}

func (o *DisableJobOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/jobs/{id}/disable][%d] disableJobOK  %+v", 200, o.Payload)
}
func (o *DisableJobOK) GetPayload() models.EmptySuccessResponse {
	return o.Payload
}

func (o *DisableJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableJobBadRequest creates a DisableJobBadRequest with default headers values
func NewDisableJobBadRequest() *DisableJobBadRequest {
	return &DisableJobBadRequest{}
}

/* DisableJobBadRequest describes a response with status code 400, with default header values.

Bad request. This error is related to POST/PUT requests. The request body is malformed, incomplete or otherwise invalid.
*/
type DisableJobBadRequest struct {
	Payload *models.Error
}

func (o *DisableJobBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/jobs/{id}/disable][%d] disableJobBadRequest  %+v", 400, o.Payload)
}
func (o *DisableJobBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DisableJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableJobUnauthorized creates a DisableJobUnauthorized with default headers values
func NewDisableJobUnauthorized() *DisableJobUnauthorized {
	return &DisableJobUnauthorized{}
}

/* DisableJobUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The authorization header has been expected but not found (or found but is expired).
*/
type DisableJobUnauthorized struct {
	Payload *models.Error
}

func (o *DisableJobUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/jobs/{id}/disable][%d] disableJobUnauthorized  %+v", 401, o.Payload)
}
func (o *DisableJobUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DisableJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableJobForbidden creates a DisableJobForbidden with default headers values
func NewDisableJobForbidden() *DisableJobForbidden {
	return &DisableJobForbidden{}
}

/* DisableJobForbidden describes a response with status code 403, with default header values.

Forbidden. The user sending the request does not have adequate privileges to access one or more objects specified in the request.
*/
type DisableJobForbidden struct {
	Payload *models.Error
}

func (o *DisableJobForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/jobs/{id}/disable][%d] disableJobForbidden  %+v", 403, o.Payload)
}
func (o *DisableJobForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DisableJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableJobNotFound creates a DisableJobNotFound with default headers values
func NewDisableJobNotFound() *DisableJobNotFound {
	return &DisableJobNotFound{}
}

/* DisableJobNotFound describes a response with status code 404, with default header values.

Not found. No object was found with the path parameter specified in the request.
*/
type DisableJobNotFound struct {
	Payload *models.Error
}

func (o *DisableJobNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/jobs/{id}/disable][%d] disableJobNotFound  %+v", 404, o.Payload)
}
func (o *DisableJobNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DisableJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableJobInternalServerError creates a DisableJobInternalServerError with default headers values
func NewDisableJobInternalServerError() *DisableJobInternalServerError {
	return &DisableJobInternalServerError{}
}

/* DisableJobInternalServerError describes a response with status code 500, with default header values.

Internal server error. The request has been received but could not be completed because of an internal error at the server side.
*/
type DisableJobInternalServerError struct {
	Payload *models.Error
}

func (o *DisableJobInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/jobs/{id}/disable][%d] disableJobInternalServerError  %+v", 500, o.Payload)
}
func (o *DisableJobInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DisableJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
