// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/veeamhub/veeam-vbr-sdk-go/models"
)

// CreateAuthorizationCodeReader is a Reader for the CreateAuthorizationCode structure.
type CreateAuthorizationCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAuthorizationCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAuthorizationCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateAuthorizationCodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateAuthorizationCodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateAuthorizationCodeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateAuthorizationCodeOK creates a CreateAuthorizationCodeOK with default headers values
func NewCreateAuthorizationCodeOK() *CreateAuthorizationCodeOK {
	return &CreateAuthorizationCodeOK{}
}

/* CreateAuthorizationCodeOK describes a response with status code 200, with default header values.

OK
*/
type CreateAuthorizationCodeOK struct {
	Payload *models.AuthorizationCodeModel
}

func (o *CreateAuthorizationCodeOK) Error() string {
	return fmt.Sprintf("[POST /api/oauth2/authorization_code][%d] createAuthorizationCodeOK  %+v", 200, o.Payload)
}
func (o *CreateAuthorizationCodeOK) GetPayload() *models.AuthorizationCodeModel {
	return o.Payload
}

func (o *CreateAuthorizationCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthorizationCodeModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthorizationCodeUnauthorized creates a CreateAuthorizationCodeUnauthorized with default headers values
func NewCreateAuthorizationCodeUnauthorized() *CreateAuthorizationCodeUnauthorized {
	return &CreateAuthorizationCodeUnauthorized{}
}

/* CreateAuthorizationCodeUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The authorization header has been expected but not found (or found but is expired).
*/
type CreateAuthorizationCodeUnauthorized struct {
	Payload *models.Error
}

func (o *CreateAuthorizationCodeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/oauth2/authorization_code][%d] createAuthorizationCodeUnauthorized  %+v", 401, o.Payload)
}
func (o *CreateAuthorizationCodeUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAuthorizationCodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthorizationCodeForbidden creates a CreateAuthorizationCodeForbidden with default headers values
func NewCreateAuthorizationCodeForbidden() *CreateAuthorizationCodeForbidden {
	return &CreateAuthorizationCodeForbidden{}
}

/* CreateAuthorizationCodeForbidden describes a response with status code 403, with default header values.

Forbidden. The user sending the request does not have adequate privileges to access one or more objects specified in the request.
*/
type CreateAuthorizationCodeForbidden struct {
	Payload *models.Error
}

func (o *CreateAuthorizationCodeForbidden) Error() string {
	return fmt.Sprintf("[POST /api/oauth2/authorization_code][%d] createAuthorizationCodeForbidden  %+v", 403, o.Payload)
}
func (o *CreateAuthorizationCodeForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAuthorizationCodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthorizationCodeInternalServerError creates a CreateAuthorizationCodeInternalServerError with default headers values
func NewCreateAuthorizationCodeInternalServerError() *CreateAuthorizationCodeInternalServerError {
	return &CreateAuthorizationCodeInternalServerError{}
}

/* CreateAuthorizationCodeInternalServerError describes a response with status code 500, with default header values.

Internal server error. The request has been received but could not be completed because of an internal error at the server side.
*/
type CreateAuthorizationCodeInternalServerError struct {
	Payload *models.Error
}

func (o *CreateAuthorizationCodeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/oauth2/authorization_code][%d] createAuthorizationCodeInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateAuthorizationCodeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAuthorizationCodeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
