// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/veeamhub/veeam-vbr-sdk-go/models"
)

// NewUpdateCredsParams creates a new UpdateCredsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateCredsParams() *UpdateCredsParams {
	return &UpdateCredsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCredsParamsWithTimeout creates a new UpdateCredsParams object
// with the ability to set a timeout on a request.
func NewUpdateCredsParamsWithTimeout(timeout time.Duration) *UpdateCredsParams {
	return &UpdateCredsParams{
		timeout: timeout,
	}
}

// NewUpdateCredsParamsWithContext creates a new UpdateCredsParams object
// with the ability to set a context for a request.
func NewUpdateCredsParamsWithContext(ctx context.Context) *UpdateCredsParams {
	return &UpdateCredsParams{
		Context: ctx,
	}
}

// NewUpdateCredsParamsWithHTTPClient creates a new UpdateCredsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateCredsParamsWithHTTPClient(client *http.Client) *UpdateCredsParams {
	return &UpdateCredsParams{
		HTTPClient: client,
	}
}

/* UpdateCredsParams contains all the parameters to send to the API endpoint
   for the update creds operation.

   Typically these are written to a http.Request.
*/
type UpdateCredsParams struct {

	// Body.
	Body *models.CredentialsModel

	/* ID.

	   ID of the credentials record.

	   Format: uuid
	*/
	ID strfmt.UUID

	/* XAPIVersion.

	     Version and revision of the client REST API. Must be in the following
	format: *\<version\>-\<revision\>*.


	     Default: "1.0-rev1"
	*/
	XAPIVersion string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update creds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCredsParams) WithDefaults() *UpdateCredsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update creds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCredsParams) SetDefaults() {
	var (
		xAPIVersionDefault = string("1.0-rev1")
	)

	val := UpdateCredsParams{
		XAPIVersion: xAPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update creds params
func (o *UpdateCredsParams) WithTimeout(timeout time.Duration) *UpdateCredsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update creds params
func (o *UpdateCredsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update creds params
func (o *UpdateCredsParams) WithContext(ctx context.Context) *UpdateCredsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update creds params
func (o *UpdateCredsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update creds params
func (o *UpdateCredsParams) WithHTTPClient(client *http.Client) *UpdateCredsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update creds params
func (o *UpdateCredsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update creds params
func (o *UpdateCredsParams) WithBody(body *models.CredentialsModel) *UpdateCredsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update creds params
func (o *UpdateCredsParams) SetBody(body *models.CredentialsModel) {
	o.Body = body
}

// WithID adds the id to the update creds params
func (o *UpdateCredsParams) WithID(id strfmt.UUID) *UpdateCredsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update creds params
func (o *UpdateCredsParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithXAPIVersion adds the xAPIVersion to the update creds params
func (o *UpdateCredsParams) WithXAPIVersion(xAPIVersion string) *UpdateCredsParams {
	o.SetXAPIVersion(xAPIVersion)
	return o
}

// SetXAPIVersion adds the xApiVersion to the update creds params
func (o *UpdateCredsParams) SetXAPIVersion(xAPIVersion string) {
	o.XAPIVersion = xAPIVersion
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCredsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// header param x-api-version
	if err := r.SetHeaderParam("x-api-version", o.XAPIVersion); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
