// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/veeamhub/veeam-vbr-sdk-go/models"
)

// GetScaleOutRepositoryReader is a Reader for the GetScaleOutRepository structure.
type GetScaleOutRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScaleOutRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScaleOutRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetScaleOutRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetScaleOutRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetScaleOutRepositoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetScaleOutRepositoryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetScaleOutRepositoryOK creates a GetScaleOutRepositoryOK with default headers values
func NewGetScaleOutRepositoryOK() *GetScaleOutRepositoryOK {
	return &GetScaleOutRepositoryOK{}
}

/* GetScaleOutRepositoryOK describes a response with status code 200, with default header values.

OK
*/
type GetScaleOutRepositoryOK struct {
	Payload *models.ScaleOutRepositoryModel
}

func (o *GetScaleOutRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupInfrastructure/scaleOutRepositories/{id}][%d] getScaleOutRepositoryOK  %+v", 200, o.Payload)
}
func (o *GetScaleOutRepositoryOK) GetPayload() *models.ScaleOutRepositoryModel {
	return o.Payload
}

func (o *GetScaleOutRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScaleOutRepositoryModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScaleOutRepositoryUnauthorized creates a GetScaleOutRepositoryUnauthorized with default headers values
func NewGetScaleOutRepositoryUnauthorized() *GetScaleOutRepositoryUnauthorized {
	return &GetScaleOutRepositoryUnauthorized{}
}

/* GetScaleOutRepositoryUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The authorization header has been expected but not found (or found but is expired).
*/
type GetScaleOutRepositoryUnauthorized struct {
	Payload *models.Error
}

func (o *GetScaleOutRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupInfrastructure/scaleOutRepositories/{id}][%d] getScaleOutRepositoryUnauthorized  %+v", 401, o.Payload)
}
func (o *GetScaleOutRepositoryUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetScaleOutRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScaleOutRepositoryForbidden creates a GetScaleOutRepositoryForbidden with default headers values
func NewGetScaleOutRepositoryForbidden() *GetScaleOutRepositoryForbidden {
	return &GetScaleOutRepositoryForbidden{}
}

/* GetScaleOutRepositoryForbidden describes a response with status code 403, with default header values.

Forbidden. The user sending the request does not have adequate privileges to access one or more objects specified in the request.
*/
type GetScaleOutRepositoryForbidden struct {
	Payload *models.Error
}

func (o *GetScaleOutRepositoryForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupInfrastructure/scaleOutRepositories/{id}][%d] getScaleOutRepositoryForbidden  %+v", 403, o.Payload)
}
func (o *GetScaleOutRepositoryForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetScaleOutRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScaleOutRepositoryNotFound creates a GetScaleOutRepositoryNotFound with default headers values
func NewGetScaleOutRepositoryNotFound() *GetScaleOutRepositoryNotFound {
	return &GetScaleOutRepositoryNotFound{}
}

/* GetScaleOutRepositoryNotFound describes a response with status code 404, with default header values.

Not found. No object was found with the path parameter specified in the request.
*/
type GetScaleOutRepositoryNotFound struct {
	Payload *models.Error
}

func (o *GetScaleOutRepositoryNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupInfrastructure/scaleOutRepositories/{id}][%d] getScaleOutRepositoryNotFound  %+v", 404, o.Payload)
}
func (o *GetScaleOutRepositoryNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetScaleOutRepositoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScaleOutRepositoryInternalServerError creates a GetScaleOutRepositoryInternalServerError with default headers values
func NewGetScaleOutRepositoryInternalServerError() *GetScaleOutRepositoryInternalServerError {
	return &GetScaleOutRepositoryInternalServerError{}
}

/* GetScaleOutRepositoryInternalServerError describes a response with status code 500, with default header values.

Internal server error. The request has been received but could not be completed because of an internal error at the server side.
*/
type GetScaleOutRepositoryInternalServerError struct {
	Payload *models.Error
}

func (o *GetScaleOutRepositoryInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/backupInfrastructure/scaleOutRepositories/{id}][%d] getScaleOutRepositoryInternalServerError  %+v", 500, o.Payload)
}
func (o *GetScaleOutRepositoryInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetScaleOutRepositoryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
