// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScaleOutRepositoryParams creates a new GetScaleOutRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetScaleOutRepositoryParams() *GetScaleOutRepositoryParams {
	return &GetScaleOutRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetScaleOutRepositoryParamsWithTimeout creates a new GetScaleOutRepositoryParams object
// with the ability to set a timeout on a request.
func NewGetScaleOutRepositoryParamsWithTimeout(timeout time.Duration) *GetScaleOutRepositoryParams {
	return &GetScaleOutRepositoryParams{
		timeout: timeout,
	}
}

// NewGetScaleOutRepositoryParamsWithContext creates a new GetScaleOutRepositoryParams object
// with the ability to set a context for a request.
func NewGetScaleOutRepositoryParamsWithContext(ctx context.Context) *GetScaleOutRepositoryParams {
	return &GetScaleOutRepositoryParams{
		Context: ctx,
	}
}

// NewGetScaleOutRepositoryParamsWithHTTPClient creates a new GetScaleOutRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetScaleOutRepositoryParamsWithHTTPClient(client *http.Client) *GetScaleOutRepositoryParams {
	return &GetScaleOutRepositoryParams{
		HTTPClient: client,
	}
}

/* GetScaleOutRepositoryParams contains all the parameters to send to the API endpoint
   for the get scale out repository operation.

   Typically these are written to a http.Request.
*/
type GetScaleOutRepositoryParams struct {

	/* ID.

	   ID of the scale-out backup repository.

	   Format: uuid
	*/
	ID strfmt.UUID

	/* XAPIVersion.

	     Version and revision of the client REST API. Must be in the following
	format: *\<version\>-\<revision\>*.


	     Default: "1.0-rev1"
	*/
	XAPIVersion string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get scale out repository params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScaleOutRepositoryParams) WithDefaults() *GetScaleOutRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get scale out repository params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScaleOutRepositoryParams) SetDefaults() {
	var (
		xAPIVersionDefault = string("1.0-rev1")
	)

	val := GetScaleOutRepositoryParams{
		XAPIVersion: xAPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get scale out repository params
func (o *GetScaleOutRepositoryParams) WithTimeout(timeout time.Duration) *GetScaleOutRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scale out repository params
func (o *GetScaleOutRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scale out repository params
func (o *GetScaleOutRepositoryParams) WithContext(ctx context.Context) *GetScaleOutRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scale out repository params
func (o *GetScaleOutRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scale out repository params
func (o *GetScaleOutRepositoryParams) WithHTTPClient(client *http.Client) *GetScaleOutRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scale out repository params
func (o *GetScaleOutRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get scale out repository params
func (o *GetScaleOutRepositoryParams) WithID(id strfmt.UUID) *GetScaleOutRepositoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get scale out repository params
func (o *GetScaleOutRepositoryParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithXAPIVersion adds the xAPIVersion to the get scale out repository params
func (o *GetScaleOutRepositoryParams) WithXAPIVersion(xAPIVersion string) *GetScaleOutRepositoryParams {
	o.SetXAPIVersion(xAPIVersion)
	return o
}

// SetXAPIVersion adds the xApiVersion to the get scale out repository params
func (o *GetScaleOutRepositoryParams) SetXAPIVersion(xAPIVersion string) {
	o.XAPIVersion = xAPIVersion
}

// WriteToRequest writes these params to a swagger request
func (o *GetScaleOutRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// header param x-api-version
	if err := r.SetHeaderParam("x-api-version", o.XAPIVersion); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
