// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GFSPolicySettingsMonthlyModel Monthly GFS retention policy.
//
// swagger:model GFSPolicySettingsMonthlyModel
type GFSPolicySettingsMonthlyModel struct {

	// Week of the month when the full backup that will be kept for archival purposes is created (the first week is the first 7 days of the month).
	DesiredTime ESennightOfMonth `json:"desiredTime,omitempty"`

	// If *true*, the monthly GFS retention policy is enabled.
	// Required: true
	IsEnabled *bool `json:"isEnabled"`

	// Number of months to keep full backups for archival purposes.
	KeepForNumberOfMonths int64 `json:"keepForNumberOfMonths,omitempty"`
}

// Validate validates this g f s policy settings monthly model
func (m *GFSPolicySettingsMonthlyModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDesiredTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIsEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GFSPolicySettingsMonthlyModel) validateDesiredTime(formats strfmt.Registry) error {
	if swag.IsZero(m.DesiredTime) { // not required
		return nil
	}

	if err := m.DesiredTime.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("desiredTime")
		}
		return err
	}

	return nil
}

func (m *GFSPolicySettingsMonthlyModel) validateIsEnabled(formats strfmt.Registry) error {

	if err := validate.Required("isEnabled", "body", m.IsEnabled); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this g f s policy settings monthly model based on the context it is used
func (m *GFSPolicySettingsMonthlyModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDesiredTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GFSPolicySettingsMonthlyModel) contextValidateDesiredTime(ctx context.Context, formats strfmt.Registry) error {

	if err := m.DesiredTime.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("desiredTime")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GFSPolicySettingsMonthlyModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GFSPolicySettingsMonthlyModel) UnmarshalBinary(b []byte) error {
	var res GFSPolicySettingsMonthlyModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
