// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SmbRepositoryShareSettingsModel Share settings.
//
// swagger:model SmbRepositoryShareSettingsModel
type SmbRepositoryShareSettingsModel struct {

	// ID of the credentials record used to access the shared folder.
	// Required: true
	// Format: uuid
	CredentialsID *strfmt.UUID `json:"credentialsId"`

	// gateway server
	GatewayServer *RepositoryShareGatewayModel `json:"gatewayServer,omitempty"`

	// Path to the shared folder that that is used as a backup repository.
	// Required: true
	SharePath *string `json:"sharePath"`
}

// Validate validates this smb repository share settings model
func (m *SmbRepositoryShareSettingsModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCredentialsID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGatewayServer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSharePath(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SmbRepositoryShareSettingsModel) validateCredentialsID(formats strfmt.Registry) error {

	if err := validate.Required("credentialsId", "body", m.CredentialsID); err != nil {
		return err
	}

	if err := validate.FormatOf("credentialsId", "body", "uuid", m.CredentialsID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SmbRepositoryShareSettingsModel) validateGatewayServer(formats strfmt.Registry) error {
	if swag.IsZero(m.GatewayServer) { // not required
		return nil
	}

	if m.GatewayServer != nil {
		if err := m.GatewayServer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gatewayServer")
			}
			return err
		}
	}

	return nil
}

func (m *SmbRepositoryShareSettingsModel) validateSharePath(formats strfmt.Registry) error {

	if err := validate.Required("sharePath", "body", m.SharePath); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this smb repository share settings model based on the context it is used
func (m *SmbRepositoryShareSettingsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGatewayServer(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SmbRepositoryShareSettingsModel) contextValidateGatewayServer(ctx context.Context, formats strfmt.Registry) error {

	if m.GatewayServer != nil {
		if err := m.GatewayServer.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gatewayServer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SmbRepositoryShareSettingsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SmbRepositoryShareSettingsModel) UnmarshalBinary(b []byte) error {
	var res SmbRepositoryShareSettingsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
