// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ViHostModel vi host model
//
// swagger:model ViHostModel
type ViHostModel struct {
	ManagedServerModel

	// Port used to communicate with the server.
	// Required: true
	Port *int64 `json:"port"`

	// vi host type
	ViHostType EViHostType `json:"viHostType,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ViHostModel) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ManagedServerModel
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ManagedServerModel = aO0

	// AO1
	var dataAO1 struct {
		Port *int64 `json:"port"`

		ViHostType EViHostType `json:"viHostType,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Port = dataAO1.Port

	m.ViHostType = dataAO1.ViHostType

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ViHostModel) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.ManagedServerModel)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Port *int64 `json:"port"`

		ViHostType EViHostType `json:"viHostType,omitempty"`
	}

	dataAO1.Port = m.Port

	dataAO1.ViHostType = m.ViHostType

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this vi host model
func (m *ViHostModel) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ManagedServerModel
	if err := m.ManagedServerModel.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateViHostType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViHostModel) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

func (m *ViHostModel) validateViHostType(formats strfmt.Registry) error {

	if swag.IsZero(m.ViHostType) { // not required
		return nil
	}

	if err := m.ViHostType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("viHostType")
		}
		return err
	}

	return nil
}

// ContextValidate validate this vi host model based on the context it is used
func (m *ViHostModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ManagedServerModel
	if err := m.ManagedServerModel.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateViHostType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViHostModel) contextValidateViHostType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.ViHostType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("viHostType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ViHostModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViHostModel) UnmarshalBinary(b []byte) error {
	var res ViHostModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
