// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ViRootFilters vi root filters
//
// swagger:model ViRootFilters
type ViRootFilters struct {

	// Maximum number of VMware vSphere servers to return.
	Limit int32 `json:"limit,omitempty"`

	// Filters VMware vSphere servers by the `nameFilter` pattern. The pattern can match any VMware vSphere server parameter. To substitute one or more characters, use the asterisk (*) character at the beginning and/or at the end.
	NameFilter string `json:"nameFilter,omitempty"`

	// Sorts VMware vSphere servers in the ascending order by the `orderColumn` parameter.
	OrderAsc bool `json:"orderAsc,omitempty"`

	// order column
	OrderColumn EViRootFiltersOrderColumn `json:"orderColumn,omitempty"`

	// Number of VMware vSphere servers to skip.
	Skip int32 `json:"skip,omitempty"`
}

// Validate validates this vi root filters
func (m *ViRootFilters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderColumn(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViRootFilters) validateOrderColumn(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderColumn) { // not required
		return nil
	}

	if err := m.OrderColumn.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("orderColumn")
		}
		return err
	}

	return nil
}

// ContextValidate validate this vi root filters based on the context it is used
func (m *ViRootFilters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrderColumn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ViRootFilters) contextValidateOrderColumn(ctx context.Context, formats strfmt.Registry) error {

	if err := m.OrderColumn.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("orderColumn")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ViRootFilters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViRootFilters) UnmarshalBinary(b []byte) error {
	var res ViRootFilters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
