// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WindowsHostComponentPortModel Ports used by Veeam Backup & Replication components.
//
// swagger:model WindowsHostComponentPortModel
type WindowsHostComponentPortModel struct {

	// component name
	// Required: true
	ComponentName *EWindowsHostComponentType `json:"componentName"`

	// Port used by the component.
	// Required: true
	Port *int64 `json:"port"`
}

// Validate validates this windows host component port model
func (m *WindowsHostComponentPortModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComponentName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WindowsHostComponentPortModel) validateComponentName(formats strfmt.Registry) error {

	if err := validate.Required("componentName", "body", m.ComponentName); err != nil {
		return err
	}

	if err := validate.Required("componentName", "body", m.ComponentName); err != nil {
		return err
	}

	if m.ComponentName != nil {
		if err := m.ComponentName.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("componentName")
			}
			return err
		}
	}

	return nil
}

func (m *WindowsHostComponentPortModel) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this windows host component port model based on the context it is used
func (m *WindowsHostComponentPortModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateComponentName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WindowsHostComponentPortModel) contextValidateComponentName(ctx context.Context, formats strfmt.Registry) error {

	if m.ComponentName != nil {
		if err := m.ComponentName.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("componentName")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WindowsHostComponentPortModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WindowsHostComponentPortModel) UnmarshalBinary(b []byte) error {
	var res WindowsHostComponentPortModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
